# Generated by Django 3.1 on 2020-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transac_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
