# Generated by Django 3.1 on 2020-10-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_transac_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
