# Generated by Django 3.1 on 2020-10-05 09:36

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201005_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.JSONField(blank=True, default=shop.models.cart, null=True),
        ),
    ]
