# Generated by Django 3.1 on 2020-10-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201005_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderitems',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
