# Generated by Django 3.1 on 2020-10-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='res_msg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
