# Generated by Django 3.1 on 2020-10-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_res_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
