# Generated by Django 3.1 on 2020-10-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_last_status_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transac_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='res_msg',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
